### ISSUE TITLE
Course Project - Proposal Discussion Signup

### ISSUE THREAD

**Issue by cmurray3** [IE-482-582/spring2024#25]
Please reply to this "issue" indicating which 30-minute time slot you would like to reserve to chat with me about your project proposal.

Due to illness, we'll have to plan to do these meetings via Zoom.  I'll share the link with you after the March 12 class.

Here are my available days/times for this week:
- Tuesday, March 12, 
    - 3:00 - 3:30pm
    - 3:30 - 4:00pm

- Wednesday, March 13:
    - 10:00 - 10:30am
    - 10:30 - 11:00am
    - 11:00 - 11:30am
    - 11:30am - noon
    - noon - 12:30pm
    - 12:30 - 1:00pm
    - 1:00 - 1:30pm
    - 1:30 - 2:00pm
    - 2:00 - 2:30pm
    - 2:30 - 3:00pm
    - 3:00 - 3:30pm
    - 3:30 - 4:00pm

Again, I just need one person from each group to claim a slot.  This is a first-come, first-served queue.

**Comment by tallan232** [comment]
Tuesday March 12th at 3:00pm for Jack Wuerfel and Thomas Allan please.  Will this be an in-person meeting or Zoom, since you're holding class on Zoom as well?  Either is fine with us, we will be on campus regardless.
Thank you.

**Comment by shardulsaptarshi** [comment]
Wednesday, March 13 at 3:00 pm for Shardul Saptarshi. Thank you!

**Comment by afifacho** [comment]
Wednesday, March 13 at 2:30 pm for Afifa Choudhury and Muhammad Asadullah.

**Comment by btle1** [comment]
Wednesday, March 13 at 12:30 pm for Brian Le and Xiaoyue Liu.

**Comment by cmurray3** [comment]
Here's the Zoom link for our meetings:
- https://buffalo.zoom.us/my/murray.zoom?pwd=SGVlUHNSY1lINDhrL0hlTytvdUs3dz09

**Comment by cmurray3** [comment]
> Wednesday, March 13 at 3:30-4:00PM, Huize will be able to attend. But I, (Kaiwen) will not be able to (due to conflict with all these times). If you would like both of us to be present please let us know, thank you.

I need all team members to be present.  Please propose some other times that you're both available tomorrow.

**Comment by BrainFog2** [comment]
> > Wednesday, March 13 at 3:30-4:00PM, Huize will be able to attend. But I, (Kaiwen) will not be able to (due to conflict with all these times). If you would like both of us to be present please let us know, thank you.
> 
> I need all team members to be present. Please propose some other times that you're both available tomorrow.

Alright, I should be available from 5:00-5:30 PM on Wednesday along with Huize. If that does not work let us know. I appreciate your flexibility.

**Comment by cmurray3** [comment]
> > > Wednesday, March 13 at 3:30-4:00PM, Huize will be able to attend. But I, (Kaiwen) will not be able to (due to conflict with all these times). If you would like both of us to be present please let us know, thank you.
> > 
> > 
> > I need all team members to be present. Please propose some other times that you're both available tomorrow.
> 
> Alright, I should be available from 5:00-5:30 PM on Wednesday along with Huize. If that does not work let us know. I appreciate your flexibility.

5-5:30 tomorrow is fine.  See you then
